<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>IPMI Server Grid</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700&display=swap" rel="stylesheet">
    @vite(['resources/css/ipmi-grid.css'])
</head>

<body class="min-h-screen pb-20 bg-gray-100">
    <!-- Fixed Header -->
    <header class="fixed top-0 left-0 right-0 z-50 bg-white shadow-md">
        <div class="header-container">
            <div class="header-content">
                <div class="header-logo">
                    <img src="{{ asset('images/logo.webp') }}" alt="Logo" class="w-auto h-10">
                    <span class="ml-3 text-lg font-bold md:text-xl neon-text">IPMI Control</span>
                </div>

                <div class="header-controls">
                    <div class="flex items-center space-x-1 md:space-x-2">

                        {{-- start: top bar search count --}}
                        <small class="text-gray-600" style="display: none;">Tìm thấy <span data-search-count>0</span> kết quả</small>
                        {{-- end: top bar search count --}}

                        {{-- start: top bar button --}}
                        <button id="btnReset" class="text-gray-500 rounded-full hover:text-gray-700 hover:bg-gray-100"
                            title="Reset">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                            </svg>
                        </button>
                        <button id="btnSettings"
                            class="text-gray-500 rounded-full hover:text-gray-700 hover:bg-gray-100" title="Settings">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                            </svg>
                        </button>
                        {{-- end: top bar button --}}

                    </div>

                    {{-- start: top bar search bar --}}
                    <div class="search-container">
                        <div class="relative w-full">
                            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                <svg class="w-4 h-4 text-gray-400" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                                </svg>
                            </div>
                            <input type="text" id="serverSearch"
                                class="block w-full py-2 pl-10 pr-3 text-sm leading-5 placeholder-gray-500 bg-white border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                                placeholder="Tìm kiếm server...">
                        </div>
                    </div>
                    {{-- end: top bar search bar --}}


                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <main class="container px-4 pt-24 mx-auto">
        <div id="ipmi-grid">
            <!-- Grid items will be generated by JavaScript -->
        </div>
    </main>

    @vite(['resources/js/ipmi-grid.js'])

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Refresh button
            const btnRefresh = document.getElementById('btnRefresh');
            if (btnRefresh) {
                btnRefresh.addEventListener('click', function() {
                    // Add your refresh logic here
                    console.log('Refresh clicked');
                    // Example: location.reload();
                });
            }

            // Settings button
            const btnSettings = document.getElementById('btnSettings');
            if (btnSettings) {
                btnSettings.addEventListener('click', function() {
                    // Add your settings logic here
                    console.log('Settings clicked');
                });
            }
        });
    </script>

</body>

</html>
