<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IPMI Server Grid</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700&display=swap" rel="stylesheet">
    @vite(['resources/css/ipmi-grid.css'])
</head>

<body class="bg-gray-100 min-h-screen pb-20">
    <!-- Fixed Header -->
    <header class="fixed top-0 left-0 right-0 bg-white shadow-md z-50">
        <div class="header-container">
            <div class="header-content">
                <div class="header-logo">
                    <img src="{{ asset('images/logo.webp') }}" alt="Logo" class="h-10 w-auto">
                    <span class="ml-3 text-lg md:text-xl font-bold neon-text">IPMI Control</span>
                </div>
                
                <div class="header-controls">
                    <div class="flex items-center space-x-1 md:space-x-2">
                        <button id="btnPower" class="text-gray-500 hover:text-gray-700 rounded-full hover:bg-gray-100"
                            title="Power Control">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M13 10V3L4 14h7v7l9-11h-7z" />
                            </svg>
                        </button>
                        <button id="btnReset" class="text-gray-500 hover:text-gray-700 rounded-full hover:bg-gray-100"
                            title="Reset">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                            </svg>
                        </button>
                        <button id="btnSettings"
                            class="text-gray-500 hover:text-gray-700 rounded-full hover:bg-gray-100" title="Settings">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                            </svg>
                        </button>
                    </div>
                    
                    <div class="search-container">
                        <div class="relative w-full">
                            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                <svg class="h-4 w-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                                </svg>
                            </div>
                            <input type="text" id="serverSearch"
                                class="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:ring-blue-500 focus:border-blue-500 text-sm"
                                placeholder="Tìm kiếm server...">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <main class="container mx-auto px-4 pt-24">
        <div id="ipmi-grid">
            <!-- Grid items will be generated by JavaScript -->
        </div>
    </main>

    <!-- Power Control Modal -->
    <div id="powerModal" class="fixed inset-0 bg-black bg-opacity-50 items-center justify-center"
        style="display: none;">
        <div class="bg-white p-6 rounded-lg shadow-xl w-64">
            <h3 class="text-lg font-semibold mb-4">Server Power Control</h3>
            <div class="space-y-2">
                <button id="btnPowerOn" class="w-full bg-green-500 hover:bg-green-600 text-white py-2 px-4 rounded">
                    Power On
                </button>
                <button id="btnPowerOff" class="w-full bg-red-500 hover:bg-red-600 text-white py-2 px-4 rounded">
                    Power Off
                </button>
                <button id="btnPowerReset"
                    class="w-full bg-yellow-500 hover:bg-yellow-600 text-white py-2 px-4 rounded">
                    Reset
                </button>
                <button id="btnCloseModal"
                    class="w-full bg-gray-300 hover:bg-gray-400 text-gray-800 py-2 px-4 rounded mt-4">
                    Close
                </button>
            </div>
        </div>
    </div>

    @vite(['resources/js/ipmi-grid.js'])

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Refresh button
            document.getElementById('btnRefresh').addEventListener('click', function() {
                // Add your refresh logic here
                console.log('Refresh clicked');
                // Example: location.reload();
            });

            // Power All On button
            document.getElementById('btnPowerAll').addEventListener('click', function() {
                if (confirm('Are you sure you want to power on all servers?')) {
                    // Add your power on all logic here
                    console.log('Power on all servers');
                }
            });

            // Shutdown All button
            document.getElementById('btnShutdownAll').addEventListener('click', function() {
                if (confirm('WARNING: This will shutdown all servers. Are you sure?')) {
                    // Add your shutdown all logic here
                    console.log('Shutdown all servers');
                }
            });

            // Settings button
            document.getElementById('btnSettings').addEventListener('click', function() {
                // Add your settings logic here
                console.log('Settings clicked');
            });
        });
    </script>
</body>

</html>
